services:
  wso2mi:
    image: wso2mi:4.2.0-alpine
    ports:
      - "8290:8290"
      - "8253:8253"
    volumes:
      - ./mi-entrypoint.sh:/home/wso2carbon/docker-entrypoint.sh:ro
      - ./integration:/home/wso2carbon/wso2mi-4.2.0/repository/deployment/server/synapse-configs/default
